<?php

add_action('plugins_loaded', function(){

	if ( ! class_exists('WebMapp_Acf') )
		return;


// DEFINIZIONE DEL DATAMODEL x ROUTE ------------------------------------------------------------------------------------------------

$field_group1 =	array(
	'key' => 'wm_route_quote',
	'title' => 'Date e preventivo',
	'fields' => array(
		array(
			'key' => 'wm_route_quote_tab_model',
			'label' => 'Modello',
			'type' => 'tab',
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'wm_route_not_salable',
			'label' => 'Route non vendibile',
			'name' => 'not_salable',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Non vendibile',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'wpml_cf_preferences' => WEBMAPP_COPY_CUSTOM_FIELD,
		),
		// array(
		// 	'key' => 'wm_route_in_promotion',
		// 	'label' => 'Route in promozione',
		// 	'name' => 'promotion',
		// 	'type' => 'true_false',
		// 	'instructions' => '',
		// 	'required' => 0,
		// 	'conditional_logic' => 0,
		// 	'wrapper' => array(
		// 		'width' => '',
		// 		'class' => '',
		// 		'id' => '',
		// 	),
		// 	'message' => 'Applica promozione',
		// 	'default_value' => 0,
		// 	'ui' => 0,
		// 	'ui_on_text' => '',
		// 	'ui_off_text' => '',
		// ),
		array(
			'key' => 'wm_route_quote_product',
			'label' => 'Modello product',
			'name' => 'product',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'product',
			),
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
			),
			'elements' => '',
			'min' => 0,
			'max' => 10,
			'return_format' => 'id',
			'wpml_cf_preferences' => WEBMAPP_COPY_CUSTOM_FIELD,
		),
		array(
			'key' => 'wm_route_quote_tab_model_season',
			'label' => 'Modello (stagioni)',
			'type' => 'tab',
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'wm_route_quote_season_repeater',
			'label' => 'Periodi di prezzo (stagionalità)',
			'wpml_cf_preferences' => WEBMAPP_COPY_CUSTOM_FIELD,
			'name' => 'model_season',
			'type' => 'repeater',
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'wm_route_quote_model_season_name',
					'wpml_cf_preferences' => WEBMAPP_TRANSLATE_CUSTOM_FIELD,
					'label' => 'Stagionalità',
					'name' => 'season_name',
					'type' => 'text',
					'instructions' => 'Inserire ad esempio: Alta Stagione, Bassa Stagione',
				),
				array(
					'key' => 'wm_route_quote_model_season_disactive',
					'label' => 'Stagione disattiva',
					'name' => 'season_disactive',
					'type' => 'true_false',
					'instructions' => 'Clicca per disattivare questa stagione',
					'wpml_cf_preferences' => WEBMAPP_COPY_CUSTOM_FIELD,
				),
				array(
					'key' => 'wm_route_quote_model_season_dates_periods_repeater',
					'label' => 'Periodi di partenza',
					'name' => 'periods',
					'type' => 'repeater',
					'layout' => 'table',
					'wpml_cf_preferences' => WEBMAPP_COPY_CUSTOM_FIELD,
					'sub_fields' => array(
						array(
							'key' => 'wm_route_quote_model_season_dates_periods_start',
							'wpml_cf_preferences' => WEBMAPP_COPY_CUSTOM_FIELD,
							'label' => 'Inizio',
							'name' => 'start',
							'type' => 'date_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'display_format' => 'd/m/Y',
							'return_format' => 'd/m/Y',
							'first_day' => 1,
						),
						array(
							'key' => 'wm_route_quote_model_season_dates_periods_stop',
							'label' => 'Fine periodo',
							'wpml_cf_preferences' => WEBMAPP_COPY_CUSTOM_FIELD,
							'name' => 'stop',
							'type' => 'date_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'display_format' => 'd/m/Y',
							'return_format' => 'd/m/Y',
							'first_day' => 1,
						),
					),
				),

				array(
					'key' => 'wm_route_quote_model_season_product',
					'label' => 'Modello product',
					'name' => 'product',
					'type' => 'relationship',
					'instructions' => 'Inserisci i modelli di prodotto creati per questa Stagionalità',
					'post_type' => array(
						0 => 'product',
					),
					'min' => 0,
					'max' => 10,
					'return_format' => 'id',
					'wpml_cf_preferences' => WEBMAPP_COPY_CUSTOM_FIELD,
				),
			),
		),
		// array(
		// 	'key' => 'wm_route_quote_tab_model_promotion',
		// 	'label' => 'Promozioni',
		// 	'type' => 'tab',
		// 	'placement' => 'top',
		// 	'endpoint' => 0,
		// 	'conditional_logic' => array(
		// 		array(
		// 			array(
		// 				'field' => 'wm_route_in_promotion',
		// 				'operator' => '==',
		// 				'value' => '1',
		// 			),
		// 		),
		// 	),
		// ),
		// array(
		// 	'key' => 'wm_route_quote_promotion_repeater',
		// 	'label' => 'Periodi di promozione',
		// 	'name' => 'model_promotion',
		// 	'type' => 'repeater',
		// 	'layout' => 'row',
		// 	'sub_fields' => array(
		// 		array(
		// 			'key' => 'wm_route_quote_model_promotion_name',
		// 			'label' => 'Nome promozione',
		// 			'name' => 'promotion_name',
		// 			'type' => 'text',
		// 		),
		// 		array(
		// 			'key' => 'wm_route_quote_model_promotion_discount',
		// 			'label' => 'Sconto',
		// 			'name' => 'promotion_value',
		// 			'type' => 'number',
		// 			'instructions' => 'Inserisci il prezzo dello sconto in Euro',
		// 		),
		// 		array(
		// 			'key' => 'wm_route_quote_model_promotion_dates_periods_repeater',
		// 			'label' => 'Periodi di partenza',
		// 			'name' => 'periods',
		// 			'type' => 'repeater',
		// 			'layout' => 'table',
		// 			'sub_fields' => array(
		// 				array(
		// 					'key' => 'wm_route_quote_model_promotion_dates_periods_start',
		// 					'label' => 'Inizio',
		// 					'name' => 'start',
		// 					'type' => 'date_picker',
		// 					'instructions' => '',
		// 					'required' => 0,
		// 					'conditional_logic' => 0,
		// 					'wrapper' => array(
		// 						'width' => '',
		// 						'class' => '',
		// 						'id' => '',
		// 					),
		// 					'display_format' => 'd/m/Y',
		// 					'return_format' => 'd/m/Y',
		// 					'first_day' => 1,
		// 				),
		// 				array(
		// 					'key' => 'wm_route_quote_model_promotion_dates_periods_stop',
		// 					'label' => 'Fine periodo',
		// 					'name' => 'stop',
		// 					'type' => 'date_picker',
		// 					'instructions' => '',
		// 					'required' => 0,
		// 					'conditional_logic' => 0,
		// 					'wrapper' => array(
		// 						'width' => '',
		// 						'class' => '',
		// 						'id' => '',
		// 					),
		// 					'display_format' => 'd/m/Y',
		// 					'return_format' => 'd/m/Y',
		// 					'first_day' => 1,
		// 				),
		// 			),
		// 		),
		// 		array(
		// 			'key' => 'wm_route_quote_model_promotion_dates_specific_repeater',
		// 			'label' => 'Date specifiche di partenza',
		// 			'name' => 'departure_dates',
		// 			'type' => 'repeater',
		// 			'instructions' => 'Inserisci una o più date per la partenza',
		// 			'required' => 0,
		// 			'conditional_logic' => 0,
		// 			'wrapper' => array(
		// 				'width' => '',
		// 				'class' => '',
		// 				'id' => '',
		// 			),
		// 			'collapsed' => 'field_model_promotion_dates_specific',
		// 			'min' => 0,
		// 			'max' => 0,
		// 			'layout' => 'table',
		// 			'button_label' => 'Aggiuni data',
		// 			'sub_fields' => array(
		// 				array(
		// 					'key' => 'wm_route_quote_model_promotion_dates_specific',
		// 					'label' => 'Data',
		// 					'name' => 'date',
		// 					'type' => 'date_picker',
		// 					'instructions' => 'Inserisci una data',
		// 					'required' => 0,
		// 					'conditional_logic' => 0,
		// 					'wrapper' => array(
		// 						'width' => '',
		// 						'class' => '',
		// 						'id' => '',
		// 					),
		// 					'display_format' => 'd/m/Y',
		// 					'return_format' => 'd/m/Y',
		// 					'first_day' => 1,
		// 				),
		// 			),
		// 		),
		// 	),
		// ),
		array(
			'key' => 'wm_route_quote_dates',
			'label' => 'Partenza (periodi di date)',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'wm_route_quote_dates_periods_repeater',
			'label' => 'Periodi di partenza',
			'name' => 'departures_periods',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'wpml_cf_preferences' => WEBMAPP_COPY_CUSTOM_FIELD,
			'sub_fields' => array(
				array(
					'key' => 'wm_route_quote_dates_period_name',
					'label' => 'Nome del periodo',
					'name' => 'period_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'wpml_cf_preferences' => WEBMAPP_TRANSLATE_CUSTOM_FIELD,
				),
				array(
					'key' => 'wm_route_quote_dates_period_start',
					'label' => 'Inizio Periodo',
					'name' => 'start',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'd/m/Y',
					'return_format' => 'd/m/Y',
					'first_day' => 1,
					'wpml_cf_preferences' => WEBMAPP_COPY_CUSTOM_FIELD,
				),
				array(
					'key' => 'wm_route_quote_dates_period_stop',
					'label' => 'Fine periodo',
					'name' => 'stop',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'd/m/Y',
					'return_format' => 'd/m/Y',
					'first_day' => 1,
					'wpml_cf_preferences' => WEBMAPP_COPY_CUSTOM_FIELD,
				),
				array(
					'key' => 'wm_route_quote_dates_period_week_days',
					'label' => 'Giorni della settimana',
					'name' => 'week_days',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'mon' => 'mon',
						'tue' => 'tue',
						'wed' => 'wed',
						'thu' => 'thu',
						'fri' => 'fri',
						'sat' => 'sat',
						'sun' => 'sun',
					),
					'allow_custom' => 0,
					'default_value' => array(),
					'layout' => 'horizontal',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
					'wpml_cf_preferences' => WEBMAPP_COPY_CUSTOM_FIELD,
				),
			),
		),
		array(
			'key' => 'wm_route_quote_dates_specific_tab',
			'label' => 'Partenza (date specifiche)',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'wm_route_quote_dates_specific_repeater',
			'label' => 'Date specifiche di partenza',
			'name' => 'departure_dates',
			'type' => 'repeater',
			'instructions' => 'Inserisci una o più date per la partenza',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5d02059174143',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Aggiuni data',
			'wpml_cf_preferences' => WEBMAPP_COPY_CUSTOM_FIELD,
			'sub_fields' => array(
				array(
					'key' => 'wm_route_quote_dates_specific',
					'label' => 'Data',
					'name' => 'date',
					'type' => 'date_picker',
					'instructions' => 'Inserisci una data',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'd/m/Y',
					'return_format' => 'd/m/Y',
					'first_day' => 1,
					'wpml_cf_preferences' => WEBMAPP_COPY_CUSTOM_FIELD,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'route',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
);



// DEFINIZIONE DEL DATAMODEL x BARCHE ------------------------------------------------------------------------------------------------
$field_group2 =	array(
	'key' => 'wm_barche',
	'title' => 'Barche info',
	'fields' => array(
		array(
			'key' => 'wm_barche_riassunto',
			'label' => 'Riassunto',
			'name' => 'riassunto',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'wm_barche_gallery',
			'label' => 'Gallery',
			'name' => 'gallery',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'insert' => 'append',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'wpml_cf_preferences' => WEBMAPP_COPY_CUSTOM_FIELD,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'barche',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
);


// DEFINIZIONE DEL DATAMODEL x la data di partenza nel Backend degli Ordini ---------------------------------------------------------------------------------------------------


$field_group3 =	array(
	'key' => 'group_5d63fd404135a',
	'title' => 'Order departure date',
	'fields' => array(
		array(
			'key' => 'field_5d63fd58692ca',
			'label' => 'Order departure date',
			'name' => 'order_departure_date',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'order-departure-date',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'shop_order',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
);


	
	new WebMapp_Acf('route',$field_group1);
	new WebMapp_Acf('barche',$field_group2);
	new WebMapp_Acf('shop_order',$field_group3);


} );